apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-notes-deployment
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-notes
  template:
    metadata:
      labels:
        app: dev-notes
    spec:
      containers:
      - name: devops-notes
        image: dev-notes/app:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: dev-notes
  namespace: devops
spec:
  selector:
    app: dev-notes
  ports:
  - port: 8070
    targetPort: 8080
    name: tcp

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-notes-ingress
  namespace: devops
  annotations:
    kubernetes.io/ingressClassName: "traefik"
spec:
  rules:
  - host: "www.192.168.56.8.sslip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dev-notes
            port: 
              number: 8070
